### ISSUE TITLE
Using robocorp.workitems fails in odd ways

### ISSUE THREAD

**Issue by mkorpela** [robocorp/robo#52]
**Current state**

I'm trying to output a single file and hitting unexpected problems.

1. To produce output I need to open workitem.inputs. This seems like irrelevant boilerplate code.
2. To get the solution running locally I seem to need to do something. I can not find what that something is.
3. When that something fails I get:

```shell
❯ rcc run
...
'Missing required environment variable: RC_WORKSPACE_ID'
==================== Full Traceback (running library_docs) =====================
Traceback (most recent call last):
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/tasks/_commands.py", line 226, in run
    task.run()
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/tasks/_task.py", line 30, in run
    self.method()
  File "/Users/.../tasks.py", line 194, in library_docs
    for _ in workitems.inputs:
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/workitems/__init__.py", line 73, in __iter__
    if self.current and not self.current.released:
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/workitems/__init__.py", line 87, in current
    return _ctx().current_input
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/tasks/_lifecycle.py", line 19, in new_func
    cache.append(next(iter_in))
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/workitems/__init__.py", line 35, in __ctx
    ctx.reserve_input()
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/workitems/_context.py", line 71, in reserve_input
    item_id = self.adapter.reserve_input()
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/workitems/_context.py", line 40, in adapter
    self._adapter = self._adapter_class()
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/workitems/_adapters.py", line 90, in __init__
    self._workspace_id: str = required_env("RC_WORKSPACE_ID")
  File "/Users/Shared/robocorp/ht/336e074_5a1fac3_9fcd2534/lib/python3.9/site-packages/robocorp/workitems/_utils.py", line 24, in required_env
    raise KeyError(f"Missing required environment variable: {name}")
KeyError: 'Missing required environment variable: RC_WORKSPACE_ID'
```

**What would be expected**

1. workitems.inputs should not be needed to create outputs.
2. I should get clear instruction when I fail to either how to fix the problem or otherwise where to find the information.
3. RC_WORKSPACE_ID seems to be something that blocks the actual problem..

**Comment by fabioz** [comment]
Regarding `RC_WORKSPACE_ID`, I agree, the error message could be better (this will be the same thing for `vault` and `assets` probably).

The docs on the vault (https://github.com/robocorp/robo/blob/master/vault/docs/guides/local-development.md) do note about it, so, maybe saying that the workspace is not linked as `RC_WORKSPACE_ID` is not set env and point to the documentation?

I also noted that the related page saying about VSCode (https://robocorp.com/docs/developer-tools/visual-studio-code/extension-features#connecting-to-control-room-vault) is outdated now (the action name is now `Robocorp: Link to Control Room` -- as the same setting is used for workitems, vault and assets. Ping @MonicaBarna to note that it needs to be updated).

**Comment by fabioz** [comment]
For workitems the linking doesn't work though, so, maybe point to something as: https://github.com/robocorp/robo/blob/master/workitems/docs/guides/local-development.md.

i.e.: users need to set `RC_WORKITEM_INPUT_PATH`, `RC_WORKITEM_OUTPUT_PATH` and `RC_WORKITEM_ADAPTER` when not using VSCode.

**Comment by osrjv** [comment]
@mkorpela, you are trying to use these libraries using plain `rcc` without VSCode + our extension, right? That also affects what the dev workflow should be. It _is_ documented to some degree in the library readme, but I agree that the error should be better.

I'll take a look at the dev workflow and think it again in light of our current offering. Much has changed since it was initially done in RPAFW.

I don't quite understand what you mean by having to "open workitems.inputs", though. You can iterate the entire queue (it's preferred, really), but it's also possible to just use the default reserved one. I'll improve that in the docs as well.
